version: '3'

services:
  app:
    build:
      context: app
    container_name: app
    tty: true
    volumes:
      - ./app:/usr/src/app
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3906:3306"
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_URL: database

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    
volumes:
  mysql:
    driver: local